from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Prp_Window(QtWidgets.QWidget):
    def setupUi(self, Prp_Window):
        Prp_Window.setObjectName("Prp_Window")
        Prp_Window.resize(809, 224)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        Prp_Window.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Resources/Images/Icon.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Prp_Window.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(Prp_Window)
        self.centralwidget.setObjectName("centralwidget")
        self.PB_OK = QtWidgets.QPushButton(self.centralwidget)
        self.PB_OK.setGeometry(QtCore.QRect(690, 150, 93, 28))
        self.PB_OK.setObjectName("PB_OK")
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(20, 130, 641, 51))
        self.frame_3.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.layoutWidget_2 = QtWidgets.QWidget(self.frame_3)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 10, 621, 30))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lbl_Data_Addr = QtWidgets.QLabel(self.layoutWidget_2)
        self.lbl_Data_Addr.setObjectName("lbl_Data_Addr")
        self.horizontalLayout_3.addWidget(self.lbl_Data_Addr)
        self.LE_DataAddr = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.LE_DataAddr.setObjectName("LE_DataAddr")
        self.horizontalLayout_3.addWidget(self.LE_DataAddr)
        self.Btn_Browse = QtWidgets.QToolButton(self.layoutWidget_2)
        self.Btn_Browse.setObjectName("Btn_Browse")
        self.horizontalLayout_3.addWidget(self.Btn_Browse)
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        self.frame_4.setGeometry(QtCore.QRect(20, 10, 191, 51))
        self.frame_4.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.layoutWidget_3 = QtWidgets.QWidget(self.frame_4)
        self.layoutWidget_3.setGeometry(QtCore.QRect(10, 10, 166, 37))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lbl_RTT = QtWidgets.QLabel(self.layoutWidget_3)
        self.lbl_RTT.setObjectName("lbl_RTT")
        self.horizontalLayout_4.addWidget(self.lbl_RTT)
        self.LE_RTT = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.LE_RTT.setObjectName("LE_RTT")
        self.horizontalLayout_4.addWidget(self.LE_RTT)
        self.lbl_sec = QtWidgets.QLabel(self.layoutWidget_3)
        self.lbl_sec.setObjectName("lbl_sec")
        self.horizontalLayout_4.addWidget(self.lbl_sec)
        self.frame_5 = QtWidgets.QFrame(self.centralwidget)
        self.frame_5.setGeometry(QtCore.QRect(20, 70, 261, 51))
        self.frame_5.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.layoutWidget_4 = QtWidgets.QWidget(self.frame_5)
        self.layoutWidget_4.setGeometry(QtCore.QRect(10, 10, 215, 37))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget_4)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lbl_CS = QtWidgets.QLabel(self.layoutWidget_4)
        self.lbl_CS.setObjectName("lbl_CS")
        self.horizontalLayout_5.addWidget(self.lbl_CS)
        self.LE_ChunkSize = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.LE_ChunkSize.setObjectName("LE_ChunkSize")
        self.horizontalLayout_5.addWidget(self.LE_ChunkSize)
        self.lbl_bits = QtWidgets.QLabel(self.layoutWidget_4)
        self.lbl_bits.setObjectName("lbl_bits")
        self.horizontalLayout_5.addWidget(self.lbl_bits)
        Prp_Window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Prp_Window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 809, 26))
        self.menubar.setObjectName("menubar")
        Prp_Window.setMenuBar(self.menubar)

        self.retranslateUi(Prp_Window)
        QtCore.QMetaObject.connectSlotsByName(Prp_Window)

    def retranslateUi(self, Prp_Window):
        _translate = QtCore.QCoreApplication.translate
        Prp_Window.setWindowTitle(_translate("Prp_Window", "Properties"))
        self.PB_OK.setText(_translate("Prp_Window", "OK"))
        self.lbl_Data_Addr.setText(_translate("Prp_Window", "Data Address"))
        self.Btn_Browse.setText(_translate("Prp_Window", "..."))
        self.lbl_RTT.setText(_translate("Prp_Window", "RTT"))
        self.lbl_sec.setText(_translate("Prp_Window", "Seconds"))
        self.lbl_CS.setText(_translate("Prp_Window", "Chunk Size"))
        self.lbl_bits.setText(_translate("Prp_Window", "Bits"))

